; =======================================================
; BATCH_CONFIG.INI
; =======================================================
[DEFAULT]
; --- 1. 路径和名称 --- 
user_home = /gpfs/share/home/2401111558
script_root = %(user_home)s/00_scripts/02_auto_starFinder/03.starpipeline.inuse/new_StarFinder
spotDecoding = %(script_root)s/01_upstream_pipeline/01_spotDecoding
FovIntegration = %(script_root)s/01_upstream_pipeline/02_FovIntegration
maskGeneration = %(script_root)s/01_upstream_pipeline/03_maskGeneration
CellReadsIntegration = %(script_root)s/01_upstream_pipeline/04_CellReadsIntegration

; data_root = %(user_home)s/01_project/08_projGBM/01_Data
; project_root = %(data_root)s/02_rawTifDir_251018
; project_name = 001_bfDecon

data_root = /dfs/share/zenghuLab/2401111558/01_project/08_projGBM/01_Data
project_root = %(data_root)s/03_rawTifDir


; data_root = /dfs/share/zenghuLab/2401111558/01_project/08_projGBM/01_Data
; project_root = %(data_root)s/11_testDataDir/012_260428_GBM0407_segTest
; project_name = 001_bfDecon


process_dir = %(user_home)s/01_project/08_projGBM/02_Process
output_root = %(process_dir)s/03_starFinder/20260428_submit002_GBM0407_segTest

spf_output = %(process_dir)s/11_spotFinding/20260130_submit001_GBM_MSspf
spd_output = %(process_dir)s/02_deconv/20260110_submit018_GBM_SeqFdecode_entropyTest
stitch_output = %(process_dir)s/04_stitching/20260505_submit001_GBM0407_IFall_reg_stitch

seg_output = %(process_dir)s/05_segmentation/clusterMap/20260504_submit001_GBM0407_NormalCM

Integ_output = %(process_dir)s/06_Integ_logs/20260506_submit001_GBM0407_integ
Eva_out = %(process_dir)s/21_EvaCheck/submit007_MSspf_EvaCheck
plotback_output = %(process_dir)s/12_plotback/20260128_submit002_GBM_MSspf

; --- 2. 默认脚本 ---
script_genelist = %(user_home)s/00_scripts/03_spotFinding/01_spotiflow/submit_genelist.sh
script_spotFinding = %(user_home)s/00_scripts/03_spotFinding/01_spotiflow/submit_spotiflow.sh
script_spotConcat = %(user_home)s/00_scripts/03_spotFinding/01_spotiflow/submit_concat.sh
script_sparse_deconv = %(user_home)s/00_scripts/01_deconvolution/02_decon-sparse.OT_250724/submit_decon.sh

script_global_reg = %(spotDecoding)s/01_global_registration.sh
script_local_reg = %(spotDecoding)s/02_local_registration_batch1.sh
script_stitch = %(spotDecoding)s/03_local_image_stitch.sh
script_decoding = %(spotDecoding)s/04_global_reads_decoding.sh
script_global_spf = %(spotDecoding)s/bak01_global_spot_finding.sh

script_IF_reg = %(FovIntegration)s/11_IF_registration.sh
script_IF_stitch_config = %(FovIntegration)s/12_IF0_meta2Coords.sh
script_IF_stitch = %(FovIntegration)s/12_IF1_stitch_fullres.slurm
script_IF_stitch_visualCheck = %(FovIntegration)s/12_IF4_stitch_visualCheck.slurm

script_dapi_cellpose = %(maskGeneration)s/01_dapi_cellpose.sh
script_clustermap = %(maskGeneration)s/11_cytoSeg_ClusterMap.sh
script_Baysor = %(maskGeneration)s/12_cytoSeg_Baysor.sh
script_ComSeg = %(maskGeneration)s/13_cytoSeg_ComSeg.sh
script_rna_restore = %(maskGeneration)s/20_restore_rna_suffix.sh

script_cellreads_integration = %(CellReadsIntegration)s/01_segResultsStitch.sh
script_csv2CountMatrix = %(CellReadsIntegration)s/02_csv2CountMatrix.sh

; MiniTest 部分脚本
; /gpfs/share/home/2401111558/00_scripts/07_ImageProcessToolkit/01_plotBack/submit_plotback.sh
script_entropyTest = %(user_home)s/00_scripts/07_ImageProcessToolkit/995_channel_entropy/submit_entropy.sh
script_plotback = %(user_home)s/00_scripts/07_ImageProcessToolkit/01_plotBack/submit_plotback.sh
script_plotbackv3 = %(user_home)s/00_scripts/07_ImageProcessToolkit/03_plotBack_v3/submit_plotback.sh
script_copymat = %(user_home)s/00_scripts/00_minitools/15_EvaTools/002_CalculateSSIM/001_copyMatFile.sh
script_ssim = %(user_home)s/00_scripts/00_minitools/15_EvaTools/002_CalculateSSIM/v251029_ssim_byRounds/submit_ssim_calcu.sh


run_genelist = false
run_spotFinding = false
run_spotConcat = false
run_sparse_deconv = false

run_global_reg = false
run_local_reg = false
run_stitch = false
run_decoding = false
run_global_spf = false

run_IF_reg = false
run_IF_stitch_config = false
run_IF_stitch = false
run_IF_stitch_visualCheck = false

run_dapi_cellpose = false
run_clustermap = false
run_Baysor = false
run_ComSeg = false
run_rna_restore = false

run_cellreads_integration = false
run_csv2CountMatrix = true

run_entropyTest = false
run_plotback = false
run_plotbackv3 = false
run_copymat = false
run_ssim = false

; --- 3. 图像参数 (可被 JOB 覆盖) ---
image_width = 2048
image_depth = 45
ref_round = 1
channel_num = 3
round_num = 11
sqrt_pieces = 4


; 斑点检测：SpotFlow 参数
gl_file_num = 3
spf_mode = LocalReg       ; LocalReg / Original / raw_preprocessed
spf_prob = 0.1
spf_partition = GPUA40
spf_array_tasks = 180
spf_parallel_tasks = 12
spf_offset = 0

; 稀疏反卷积参数
sd_project_root = %(data_root)s/001_bfDeconv
sd_offset = 0
sd_pixelsize = 108.33
sd_sigma_gaussian = 100

sd_fidelity = 300
sd_sparsity = 15
sd_percennorm = 99.9995
sd_hessian_iter = 100
sd_sparse_iter_total = 16

sd_resolution = 340
sd_numerical_aperture = 1.42
sd_wavelengthmode = Olympus
sd_chunksize = 2304
sd_overlap = 60
sd_decon_type = 1
sd_continuity = 0.1
sd_background = 0
sd_enable_refineResolution = false
sd_enable_Guassblur = False
sd_enable_upsample = False
sd_partition = GPUA800
sd_array_tasks = 240    ; fovs * 3
sd_parallel_tasks = 12


; --- 4. 步骤 1: GLOBAL_REGISTRATION ---
gr_norm_mode = percentile
gr_percen_max = 100             ; 99.999
gr_percen_min = 0
gr_hist_round = 0
gr_hist_channel = 0
gr_radius = 8
gr_mode = 1
gr_align_basis = maxProjection
gr_erode = 1
gr_transform = 1
gr_input_format = uint16
gr_norm_out_format = uint8

gr_partition = C64M512G
gr_cpus = 16
gr_array_tasks = 388
gr_parallel_tasks = 1024  ; 注意: ini 中用 %%
gr_offset = 0


; --- 5. 步骤 2: LOCAL_REGISTRATION ---
lr_align_basis = maxProjection
lr_partition = C64M512G
lr_cpus = 8
lr_array_tasks = 388
lr_parallel_tasks = 1024
lr_offset = 0

; --- 6. 步骤 3: LOCAL_STITCH ---
ls_partition = C64M512G
ls_cpus = 8
ls_array_tasks = 388
ls_parallel_tasks = 1024 ; 示例中是 64
ls_offset = 0

; --- 7. 步骤 4: GLOBAL_DECODING ---
gd_intensity_threshold = 0.2 ; 代表是第二次运行的结果
gd_spotfinding_method = max3d ; 示例中是 SpotFlow
gd_decoding_mode = normal             ; # normal / seqD / seqF / seqDF
gd_codeMap_mode = Leica_rj           ; # Olympus / Leica_rj
gd_loading_mode = local_registration
gd_intensityThresh_PR = 0
gd_voxelsize = 1,1,1
gd_decoding_rounds = 11
gd_partition = C64M512G
gd_cpus = 8
gd_array_tasks = 388
gd_parallel_tasks = 1024 ; 示例中是 64
gd_offset = 0

; --- 8. 步骤 5: GLOBAL_SPOT_FINDING ---
gspf_intensity_threshold = 0.2 ; 示例中是 0.1
gspf_spotfinding_method = max3d ; 示例中是 SpotFlow
gspf_loading_mode = global_registration      ; local_registration
gspf_partition = C64M512G
gspf_cpus = 8
gspf_array_tasks = 388
gspf_parallel_tasks = 1024
gspf_offset = 0


; --- 10. 步骤 6 (IF Reg) 参数 ---
if_reg_input_format = uint16
if_reg_norm_out_format = uint8
if_reg_protein_outdir = IFnew_uint8
if_reg_offset = 0

if_reg_partition = C64M512G
if_reg_cpus = 8
if_reg_array_tasks = 8
if_reg_parallel_tasks = 1024


; --- 步骤 (IF Stitch2Config) 参数 ---
; INPUT_DIR=$1
; OUTPUT_DIR=$2
; MATCH_STRING=$3
; pixel_size_um=$4
; image_xy=$5
; overlap_ratio=$6
; INVERT_Y_FLAG=${7:-""}      # --invert_y

; maf_file=$8
; position_offset=$9
; microscope=$10      # Leica or Olympus

; Leica
if_stitch_config_input_dir = /gpfs/share/home/2401111558/labShare/2401111558/01_project/08_projGBM/01_Data/03_rawTifDir/GBM001/02_registration001_GBM001_NormalDecode/IFnew_uint8/ref-DAPI
if_stitch_config_match_string = Position

if_stitch_config_pixel_size_um = 0.142
if_stitch_config_image_xy = 2048
if_stitch_config_overlap_ratio = 0.1
if_stitch_config_invert_y_flag = ""

if_stitch_config_maf_file = /gpfs/share/home/2401111558/labShare/2401111558/01_project/08_projGBM/01_Data/03_rawTifDir/output_2026-04-10_A2A3.maf
if_stitch_config_position_offset = 0
if_stitch_config_microscope = Leica

if_stitch_config_partition = C64M256G
if_stitch_config_cpus = 16
if_stitch_config_mem = 64G


; ; Olympus
; if_stitch_config_input_dir = %(user_home)s/01_project/08_projGBM/01_Data/21_rawData_251011/251005_GBM_1-4/005_seqD5/20251021_GBM_1_251005_SeqD5
; if_stitch_config_match_string = C3
; if_stitch_config_pixel_size_um = 0.1083333
; if_stitch_config_image_xy = 2304
; if_stitch_config_overlap_ratio = 0.1
; if_stitch_config_invert_y_flag = ""
; if_stitch_config_maf_file = ""
; if_stitch_config_position_offset = 0
; if_stitch_config_microscope = Olympus

; if_stitch_config_partition = C64M256G
; if_stitch_config_cpus = 16
; if_stitch_config_mem = 64G


; --- 11. 步骤 7 (IF Stitch) 参数 ---
if_stitch_grid_x = 1
if_stitch_grid_y = 1
if_stitch_first_index = 1
if_stitch_stitch_pattern = Positions_from_file

if_stitch_partition = C64M512G
if_stitch_cpus = 60
if_stitch_mem = 480G


; --- IF Stitch VisualCheck 参数 ---
if_stitch_visualCheck_grid_x = 1
if_stitch_visualCheck_grid_y = 1
if_stitch_visualCheck_first_index = 1
if_stitch_visualCheck_stitch_pattern = Positions_from_file

if_stitch_visualCheck_partition = C64M512G
if_stitch_visualCheck_cpus = 62
if_stitch_visualCheck_mem = 496G


; --- 12. 步骤 8 (DAPI Cellpose) 参数 ---
dapi_cp_diameter = 100
dapi_cp_partition = GPUA40
dapi_cp_array_tasks = 60
dapi_cp_parallel_tasks = 12
dapi_cp_area_thresh = 1600
dapi_cp_offset = 0


; --- 13. 步骤 9 (ClusterMap) 参数 ---
cluMap_cell_num_thresh = 0.1
cluMap_dapi_grid = 4
cluMap_cell_radius = 40,15
cluMap_pct_filter = 0.01
cluMap_rotation = 90
cluMap_extra_preprocess = F
cluMap_sub_Span = 400
cluMap_expected_workers = 1
cluMap_reads_filters = 5
cluMap_overlap_percent = 0.2
cluMap_dapi_suffix = ch03.tif
cluMap_spot_csv_name = goodPoints_max3d_0.2_tri.csv
cluMap_offset = 0

cluMap_partition = C64M512G
cluMap_cpus = 32
cluMap_array_tasks = 6
cluMap_parallel_tasks = 1024

; rna_restore 参数
; input_dir=$1
; segout_dir=$2

; raw_csv=$3
; remained_csv=$4
; output_csv=$5

; img_c=$6
; img_r=$7
; rotation_deg=$8
; tolerance=$9
; OFFSET=${10:-0}
rna_restore_segout_dir = clustermap
rna_restore_raw_csv = goodPoints_max3d_0.2_tri.csv
rna_restore_remained_csv = remain_reads_raw.csv
rna_restore_output_csv = remain_reads_assigned.csv
rna_restore_img_c = 2048
rna_restore_img_r = 2048
rna_restore_rotation_deg = 90
rna_restore_tolerance = 2
rna_restore_offset = 0

rna_restore_partition = C64M512G
rna_restore_cpus = 2
rna_restore_mem = 16G
rna_restore_array_tasks = 192
rna_restore_parallel_tasks = 1024


; cellreads_integration 参数
cr_core_script = %(CellReadsIntegration)s/segResultsStitch_v1_20260112.py
cr_seg_method = clustermap
cr_if_dirname = IFnew_uint8
cr_suffix = 260506_GBM0407

cr_partition = C64M512G
cr_cpus = 60

; csv2CountMatrix 参数
c2cm_core_script = %(CellReadsIntegration)s/csv2CountMatrix.py
c2cm_partition = C64M512G
c2cm_cpus = 8
c2cm_mem = 64G


; entropyTest 参数
; et_spot_name = allSpots_spotiflow.csv
; et_image_name = localRegistered_image.mat
; et_prefix = entropyTest_
; et_offset = 0

; et_partition = C64M512G
; et_cpus = 8
; et_array_tasks = 60
; et_parallel_tasks = 128
; entropyTest 参数
et_spot_name = allSpots_max3d_0.2.csv
et_image_name = rawPreprocessed_image.mat
et_outdir = ""
et_prefix = entropyTest_r1_0p2
et_process_rounds = 0 ; a-b 或 a 指定处理轮，其他非法情况（如0）处理所有轮
et_extend_size = [3,3,3]
et_offset = 0

et_partition = C64M512G
et_cpus = 8
et_array_tasks = 60
et_parallel_tasks = 1024

; plotback 参数
pb_csv_name = allSpots_max3d_0.2
pb_offset = 0

pb_partition = C64M512G
pb_cpus = 4
pb_array_tasks = 60
pb_parallel_tasks = 256


; plotbackv3 参数
; R_DIR="$1"
; R_FILE_SUFFIX="$2"
; G_DIR="$3"
; G_FILE_SUFFIX="$4"
; B_DIR="$5"
; B_FILE_SUFFIX="$6"
; OUTPUT_DIR="$7"
; PREFIX="${8:-""}"

; R_FILE_Class="${9:-"csvfile"}"
; G_FILE_Class="${10:-"tifffile"}"
; B_FILE_Class="${11:-"tifffile"}"
; REF_ROUND="${12:-1}"
pbv3_r_dir = 001_OT20X3.2_A2_5ADVMLE
pbv3_r_file_suffix = allSpots_max3d_0.2
pbv3_g_dir = 001_OT20X3.2_A2_5ADVMLE
pbv3_g_file_suffix = rawMorphoRecon
pbv3_b_dir = 001_OT20X3.2_A2_5ADVMLE
pbv3_b_file_suffix = rawNorm

pbv3_r_file_class = csvfile
pbv3_g_file_class = tifffile
pbv3_b_file_class = tifffile
pbv3_offset = 0

pbv3_partition = C64M512G
pbv3_cpus = 4
pbv3_array_tasks = 60
pbv3_parallel_tasks = 256


; copymat 参数
cpm_filename = globalRegistered_image.mat ; globalRegistered_image

cpm_partition = C64M512G
cpm_cpus = 1

; ssim 参数
ssim_partition = GPUA40
ssim_array_tasks = 60
ssim_parallel_tasks = 12
ssim_offset = 0



[JOB_001]
project_name = GBM001
regDir_suffix = 001_GBM001_NormalDecode
job_suffix = 001_GBM001_integ


[JOB_002]
project_name = GBM002
regDir_suffix = 001_GBM002_NormalDecode
job_suffix = 002_GBM002_integ
