#!/usr/bin/env python3
# generate_TileConfiguration.py
# Generate TileConfiguration.txt for Fiji/ImageJ stitching from a FOV layout CSV.

import csv
import re
import argparse
import os


def read_csv_grid(filepath):
    """
    Read a CSV file containing FOV numbers and return a 2D list of integers.

    Parameters:
        filepath (str): Path to the input CSV file.

    Returns:
        List[List[int]]: 2D grid of FOV numbers, or None on error.
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"CSV file not found: {filepath}")

    grid = []
    try:
        with open(filepath, 'r', newline='', encoding='utf-8') as csvfile:
            reader = csv.reader(csvfile)
            for row in reader:
                if not row:  # skip empty lines
                    continue
                grid.append([int(cell) for cell in row])
        if not grid or not grid[0]:
            raise ValueError("CSV file is empty or malformed.")
        print(f"Successfully loaded grid: {len(grid)} rows x {len(grid[0])} columns.")
        return grid
    except (ValueError, OSError) as e:
        raise ValueError(f"Failed to parse CSV file '{filepath}': {e}")


def parse_overlap(overlap_input):
    """
    Parse overlap input that may be a decimal (e.g., 0.1) or percentage (e.g., '10%').

    Returns:
        float: Overlap as a decimal between 0.0 and 1.0 (exclusive).
    """
    match = re.search(r'[0-9.]+', str(overlap_input))
    if not match:
        raise ValueError("Overlap must contain a valid number (e.g., 0.1 or 10%).")

    value = float(match.group(0))
    if '%' in str(overlap_input):
        value /= 100.0

    if not (0.0 <= value < 1.0):
        raise ValueError("Overlap must be in the range [0, 1).")

    return value


def generate_tile_configuration(grid, fov_x, fov_y, overlap, filename_prefix="Position"):
    """
    Generate the content of TileConfiguration.txt for ImageJ/Fiji stitching.

    Parameters:
        grid (List[List[int]]): 2D layout of FOV numbers.
        fov_x (int): Width of a single FOV in pixels.
        fov_y (int): Height of a single FOV in pixels.
        overlap (float): Overlap ratio (e.g., 0.1 for 10%).
        filename_prefix (str): Prefix for image filenames (e.g., "Position").

    Returns:
        str: Full content of TileConfiguration.txt.
    """
    step_x = fov_x * (1 - overlap)
    step_y = fov_y * (1 - overlap)
    print(f"Calculated step size: X = {step_x:.2f}, Y = {step_y:.2f}")

    lines = [
        "# Define the number of dimensions we are working on",
        "dim = 3",
        "",
        "# Define the image coordinates (Top-Left Origin)"
    ]

    for row_idx, row in enumerate(grid):
        for col_idx, fov_num in enumerate(row):
            x = col_idx * step_x
            y = row_idx * step_y
            z = 0.0
            filename = f"{filename_prefix}{fov_num:03d}.tif"
            lines.append(f"{filename}; ; ({x:.1f}, {y:.1f}, {z:.1f})")
        lines.append("")  # blank line between rows for readability

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate TileConfiguration.txt for ImageJ/Fiji stitching "
                    "from a FOV numbering CSV file."
    )
    parser.add_argument( "--csv", required=True,
        help="Path to the FOV layout CSV file (generated by generate_tile_position.py).")
    parser.add_argument( "--fov-size", required=True, metavar="X,Y",
        help="FOV size in pixels as 'width,height' (e.g., 2304,2304). Z-dimension is ignored.")
    parser.add_argument( "--overlap", required=True,
        help="Overlap between adjacent tiles, as a decimal (0.1) or percentage (10%%).")
    parser.add_argument( "--prefix", default="Position",
        help="Filename prefix for tile images (default: 'Position').")
    parser.add_argument( "--output", default="TileConfiguration.txt",
        help="Output filename (default: TileConfiguration.txt).")


    args = parser.parse_args()

    # Parse FOV size
    try:
        fov_parts = args.fov_size.split(',')
        if len(fov_parts) != 2:
            raise ValueError("FOV size must be two integers separated by comma (e.g., 2304,2304).")
        fov_x = int(fov_parts[0])
        fov_y = int(fov_parts[1])
        if fov_x <= 0 or fov_y <= 0:
            raise ValueError("FOV width and height must be positive integers.")
    except Exception as e:
        parser.error(f"Invalid --fov-size: {e}")

    # Parse overlap
    try:
        overlap = parse_overlap(args.overlap)
    except ValueError as e:
        parser.error(f"Invalid --overlap: {e}")

    # Read grid
    try:
        grid = read_csv_grid(args.csv)
    except (FileNotFoundError, ValueError) as e:
        parser.error(str(e))

    # Generate configuration
    try:
        config_content = generate_tile_configuration(
            grid=grid,
            fov_x=fov_x,
            fov_y=fov_y,
            overlap=overlap,
            filename_prefix=args.prefix
        )
    except Exception as e:
        parser.error(f"Failed to generate TileConfiguration: {e}")

    # Write output
    try:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(config_content)
        print(f"\nSuccessfully wrote TileConfiguration to: '{args.output}'")
    except OSError as e:
        parser.error(f"Failed to write output file: {e}")


if __name__ == "__main__":
    main()